# Generated by Django 5.0.2 on 2024-02-22 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_alter_flashcard_pergunta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondido', models.BooleanField(default=False)),
                ('acertou', models.BooleanField(default=False)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flashcard.flashcard')),
            ],
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('quantidade_perguntas', models.IntegerField()),
                ('dificuldade', models.CharField(choices=[('1', 'Semana 1'), ('2', 'Semana 2'), ('3', 'Semana 3'), ('4', 'Semana 4'), ('5', 'Semana 5'), ('6', 'Semana 6'), ('7', 'Semana 7')], max_length=1)),
                ('categoria', models.ManyToManyField(to='flashcard.categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('flashcards', models.ManyToManyField(to='flashcard.flashcarddesafio')),
            ],
        ),
    ]
